import type { Metadata } from 'next';
import { NextAuthProvider } from "./Providers";
import { Roboto, Exo_2, Playfair_Display } from 'next/font/google';
import '@styles/style.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Header from '@common/Header';
import { DotaProvider } from '@dota/DotaContext';

export const metadata: Metadata = {
	title: 'Create Next App',
  	description: 'Generated by create next app',
}

export default function RootLayout({children})
{
  	return (
    	<html lang="en">
			<body>	
					<NextAuthProvider>
						<DotaProvider>
							<Header/>	
							<main>{children}</main>
						</DotaProvider>
					</NextAuthProvider>
			</body>
    	</html>
  	)
}
